### ISSUE TITLE
Services API docs validation lookup table impossible

### ISSUE THREAD

**Issue by SamuelMarks** [cloudfoundry/docs-services#107]
I'm writing a custom V2 service broker, and what to be standards compliant.

But with `GET /v2/catalog` for example: `id` is mentioned 3 times, `name` twice and `description` twice. Please review the docs and dedupe!

https://github.com/cloudfoundry/docs-services/blob/f92440d3ae48c3b1561f4f6968e53967737dd2b9/api.html.md.erb

**Comment by dieucao** [comment]
@SamuelMarks 
Do you mean the table under
http://docs.cloudfoundry.org/services/api.html#catalog-mgmt

It may be difficult to see, but there are indentations which are supposed to help represent nesting.
So the first id is the service id, the second id is for the plan nested under plans, the third is is for the OAuth2 client nested under dashboard_client.
Similarly for name and description.

Does the example just below the table help to explain?

**Comment by SamuelMarks** [comment]
Oh right, I see it now. Any chance of emphasising that e.g.: the second ID is for *purpose*?

Ditto for route paths

**Comment by abbyachau** [comment]
Hi @SamuelMarks, many thanks for raising this issue. We've updated the table on the catalog management page: http://docs.cloudfoundry.org/services/api.html#catalog-mgmt. Thanks again!

Best,

Abby

**Comment by SamuelMarks** [comment]
Thanks, that's much more readable
