### ISSUE TITLE
Last modified date garbled in safari

### ISSUE THREAD

**Issue by srl295** [cloudfoundry/docs-services#114]
https://docs.cloudfoundry.org/services/binding-credentials.html  in Safari shows at the top: 
> Page last updated: 3 de marzo de 5877521, -8:-31:-23 GMT-7:52:58 NaN, NaN

Locale is "es-US", Safari Versión 9.0.3 (11601.4.4)

**Comment by animatedmax** [comment]
Hello @srl295 This issue should now be resolved. Thank you!

**Comment by srl295** [comment]
@animatedmax how did you fix it?

**Comment by animatedmax** [comment]
@srl295 We changed the javascript in the source code that builds the documents. We were using:
```
var lastModifiedDate = new Date($el.data().modifiedDate);
var month = lastModifiedDate.toLocaleString('en-us', {month: 'long'});
```

Now we're using:
```
var lastModifiedDate = new Date.parse($el.data().modifiedDate.replace(" UTC", ""));
var month = lastModifiedDate.toString('MMMM');
```

**Comment by srl295** [comment]
@animatedmax interesting… but Date.toString() doesn't take parameters like that- is this in some polyfill?

**Comment by animatedmax** [comment]
@srl295 Sorry, I should have shown you the whole commit that fixed the issue: 
https://github.com/pivotal-cf/docs-layout-repo/commit/2bb4f24078a880f87acb7112b6edafef1b8834ce

Hope that helps!

**Comment by srl295** [comment]
@animatedmax ah - it's using datejs - https://github.com/datejs/Datejs#converting-to-string - thanks. Good day!
