### ISSUE TITLE
Docs should indicate that route services require diego 

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/docs-services#122]
Diego appears to be required to use route services, but this isn't mentioned in the docs at http://docs.cloudfoundry.org/services/route-services.html. This would be a useful point to include.

By the way, here's the error message on attempting to bind a route service without diego:

```
FAILED
Server error, status code: 400, error code: 60020, message: Route services are only supported for apps on Diego. Unbind the service instance from the route or enable Diego for the app.
```

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @jmcarp. We've added a note that advises users that Route Services require Diego.
