### ISSUE TITLE
Required fields for `last_operation` request in API 2.9

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry/docs-services#128]
New query parameters were added to the `last_operation` request in API version 2.9: `service_id`, `plan_id`, and `operation`. The `service_id` and `plan_id` query parameters are [marked as required](https://github.com/cloudfoundry/docs-services/blob/master/api-v2.9.html.md.erb#L444-L453) in the 2.9 docs. 

The example `curl` command below the parameters table does not show these parameters in the query string, and it would be typical for newly added parameters to be optional for backward compatibility. 

Are these two parameters really required?

**Comment by bentarnoff** [comment]
Hi @scottfrederick, thanks for bringing this to our attention. These request query parameters are not strictly required, but Cloud Controller will include them on all `last_operation` requests that it makes to service brokers. I will update the topic to clarify. I'm closing this issue for now but please feel free to be in touch if you have any further feedback. Thanks.

**Comment by scottfrederick** [comment]
That makes sense @bentarnoff. Seeing "required" on those query params might lead someone to believe that a broker was required to handle them, which I didn't think was the case. "Always sent" vs "conditionally sent" (e.g. the `operations` parameter) makes sense. Thanks for clarifying.
