### ISSUE TITLE
Link to GoRouter spec is incorrect

### ISSUE THREAD

**Issue by sax** [cloudfoundry/docs-services#129]
The [Enabling Route Services in CloudFoundry](https://docs.cloudfoundry.org/services/route-services.html#enabling-route-services-in-cloudfoundry) section provides a link to the GoRouter spec. This link is no longer correct, so results in a 404 page.

**Comment by ljarzynski** [comment]
Hi @sax, do you by any chance know what the correct link would be?

**Comment by sax** [comment]
I suspect that it is https://github.com/cloudfoundry-incubator/routing-release/blob/master/jobs/gorouter/spec, but I would verify with the routing team.

**Comment by ljarzynski** [comment]
@sax - Thanks for filing this issue. I made the following commits to fix the link after discussing with the routing team:
https://github.com/cloudfoundry/docs-services/commit/afbdb20cb96f61944f470f371186361d3cb55e51
https://github.com/cloudfoundry/docs-book-cloudfoundry/commit/8618ff5b5396c0bd0af9745a123533e6b6c33c72
