### ISSUE TITLE
Provision body example is incorrect

### ISSUE THREAD

**Issue by Jamstah** [cloudfoundry/docs-services#132]
Not sure why, but if you look at the response body example on the web (https://docs.cloudfoundry.org/services/api.html#provisioning), dashboard_url is mistakenly printed as dashboardurl. The url part is italicised, so I'm guessing that the underscores are being interpreted as markdown.

This doesn't happen to the other examples. Maybe it needs two spaces at the start of the line?

**Comment by bentarnoff** [comment]
Please see https://github.com/cloudfoundry/docs-services/pull/133. Thanks!
