### ISSUE TITLE
changelog has not been updated for two versions

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/docs-services#139]
@SocalNick @tedsuo @dieucao 

The broker API changelog was introduced to provide documentation to broker authors about when new versions were introduced, what changed in each version (this is also documented in the version specific docs), and what changes were made to the docs that did not impact the api spec. For example, we used to get questions that made us realize our docs were wrong, or required clarification. If a broker author revisits the docs and sees that the content has changed without a version bump, the changelog explains that this change occurred. 

The last entry in the changelog is 2015-11-08, when 2.8 of the spec was released. There have been two versions since then. It appears the changelog is not being maintained. I would suggest   CAPI commit to keeping it updated, add an entry declaring deprecation, or remove it.

**Comment by SocalNick** [comment]
Thanks @shalako, we have been updating each Changes Since, wasn't aware of this other page. We'll fix.

**Comment by youreddy** [comment]
Hello @shalako,

I submitted a [pull request](https://github.com/cloudfoundry/docs-services/pull/140) to update the change log. When you feel that your issue has been resolved, please go ahead and close it.

Thanks for bringing this to our attention!

@youreddy
CF CAPI TEAM

**Comment by ljarzynski** [comment]
@shalako See staging link: http://docs-cloudfoundry-staging.cfapps.io/services/v2-api-changelog.html. Will be live next prod push.

**Comment by shalako** [comment]
Please clarify the changelog entry made for 2.9 on 2016-06-14. Quite confusing.

Looking at the API, I might suggest:

- Last operation endpoint now supports `service_id` and `plan_id` as request parameters
- Brokers may now optionally return `operation` field in responses for Provision, Update, and Deprovision. Broker clients may provide this same object as a request parameter when polling Last operation.

**Comment by bentarnoff** [comment]
Please see the latest edits: http://docs-cloudfoundry-staging.cfapps.io/services/v2-api-changelog.html

**Comment by shalako** [comment]
Much better, thanks

**Comment by bentarnoff** [comment]
Great, thanks @shalako. Closing.
