### ISSUE TITLE
Service names must be unique

### ISSUE THREAD

**Issue by rboykin** [cloudfoundry/docs-services#141]
It should be made clear in the documentation that a service name must be unique, similarly to the id of the service.  This is ultimately required by the CCDB services' table indices.

As a reference, here is the description for the service id:

An identifier used to correlate this service in future requests to the catalog. This must be unique within Cloud Foundry, using a GUID is recommended.

**Comment by bentarnoff** [comment]
Hey @rboykin thanks for bringing this to our attention. Did you have a particular topic within http://docs.cloudfoundry.org/services/ where you wanted to see this change?

**Comment by rboykin** [comment]
@bentarnoff  Seems like it should be clear as a restriction in the values returned from the /v2/catalog call.  Namely the service name field found within this section http://docs.cloudfoundry.org/services/api.html#catalog-mgmt  Within the actual file I find it here https://github.com/cloudfoundry/docs-services/blob/master/api.html.md.erb#L176

**Comment by bentarnoff** [comment]
Hey @rboykin I've updated the topic to reflect the fact that service names must be unique. You can see the revised topic on our staging site here: http://docs-cloudfoundry-staging.cfapps.io/services/api.html#catalog-mgmt. Thanks for the feedback, and don't hesitate to get in touch in the future.

**Comment by rboykin** [comment]
Thanks @bentarnoff
