### ISSUE TITLE
new operations parameters missing (reducing state in service brokers)

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-services#144]
I understand the merged PRs https://github.com/cloudfoundry/cloud_controller_ng/pull/611 and https://github.com/cloudfoundry/cloud_controller_ng/pull/592 added new "operation" parameters to provision, update and unprovision endpoints, according to the following [design proposal](
https://docs.google.com/document/d/1QzrG3d9-RgB7v5W44jnwgDuQWgqqPosASyCunLwfYF0/edit)

However, I don't see the associated specification updated in the docs-services repo (in change log or fields added)

**Comment by pspinrad** [comment]
Thanks gberche-orange-- can you please write a heading and a sentence or two explaining what the new params are and why they're handy?  Or ping me and I'd be happy and discuss (and learn).
Besides in a change log, I'm thinking this new info belongs in or near the existing documentation of provision, update, and deprovision status codes:
> http://docs.pivotal.io/pivotalcf/1-8/services/api.html#polling
...but let me know if I'm missing something and it belongs elsewhere.  Thanks again!

**Comment by avade** [comment]
https://github.com/cloudfoundry/docs-services/blob/master/api.html.md.erb#L453

Also see the Provision / Update docs as they also show how to return this field.

**Comment by gberche-orange** [comment]
@avade @pspinrad thanks for your responses.

I now see the parameters are indeed documented and present the in [changelog for version 2.9](http://docs.cloudfoundry.org/services/v2-api-changelog.html) 

I had read too fast and and missed them, sorry about that. My apologies for the noise and extra work for handling this invalid issue.

**Comment by pspinrad** [comment]
No worries-- thanks for your kind follow-up.

**Comment by gberche-orange** [comment]
@avade  @pspinrad I was wondering whether there are size restrictions on the new "operation" string returned on the body of the [provisioning](http://docs.cloudfoundry.org/services/api.html#provisioning) and [update](http://docs.cloudfoundry.org/services/api.html#updating_service_instance): we are planning to base64 encode approx 1KB of data into this field and are wondering the operational impact this could have.

Looking at the [PR](https://github.com/cloudfoundry/cloud_controller_ng/pull/611), I quickly searched for size restriction on the operation field, and could only see potential limitation on the cc_db. The [schema migration](https://github.com/cloudfoundry/cloud_controller_ng/blob/057274f0d116cc7c1567411e97a04859e0a21402/db/migrations/20160601165902_add_broker_provided_operation_to_instance_last_operation.rb#L4) seems to declare the field as a TEXT column (from [Sequel datatype](http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-Column+types)). On mysql, the TEXT seems a variable length datatype according to [1](http://dev.mysql.com/doc/refman/5.7/en/blob.html) and [2](http://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html). On postgresql, it is also a [variable unlimited length](https://www.postgresql.org/docs/9.1/static/datatype-character.html).

I therefore conclude that the operation string can technically be arbitrarily long but in practice too large strings (>10 kb) will put load on the CC db, so reasonable (less than 1 KB) should be preferred.

/CC @poblin-orange @tinygrasshopper

The current documentation does not seem to yet document size/length restrictions on any field. So I guess that if a section on size restriction would be useful to readers, that would rather be a generic section such as the one on [errors](http://docs.cloudfoundry.org/services/api.html#broker-errors)

**Comment by avade** [comment]
@craigfurman apart from the DB column type we didn't add any size restrictions on `operation` data returned from the service broker did we? What is our average payload size for the data our broker returns?

It seems like it would be a good idea to restrict this, but I am not sure what would be a suitable size.

**Comment by craigfurman** [comment]
@avade I don't think we restrict this, but yes we probably should, to guard against malicious / buggy brokers that return enormous operation data strings to avoid filling up the CC DB.

CC will then be sending the `operation` in the URL query, which some servers restrict to a few KB. nginx does this, off the top of my head.

In any case we keep something that looks like this in the operation data:
```json
{
  "bosh_task_id": 7,
  "lifecycle_phase": "create"
}
```

A limit of ~1000 chars will be fine for practical use of ODB

**Comment by avade** [comment]
@gberche-orange let's move this discussion to https://github.com/cloudfoundry/cloud_controller_ng/issues/695

**Comment by gberche-orange** [comment]
thanks @avade and @craigfurman for your analysis and the follow up into a dedicated issue.
