### ISSUE TITLE
Missing documentation for max_db_per_node

### ISSUE THREAD

**Issue by Samze** [cloudfoundry/docs-services#152]
The `/v2/catalog` response service object has a `max_db_per_node` [field](https://github.com/cloudfoundry/docs-services/blob/master/api.html.md.erb#L157-L159) but it does not have any accompanying documentation.

What is this property?

**Comment by pspinrad** [comment]
Hi @rizwanreza Please, can you help @Samze with this issue? The meaning of this field `max_db_per_node` is suspiciously missing in the Service Objects table under here: http://docs.pivotal.io/pivotalcf/1-9/services/api.html#catalog-mgmt
Thanks in advance,

**Comment by avade** [comment]
@SocalNick / @utako any idea about this field?

**Comment by SocalNick** [comment]
No clue, @shalako?

**Comment by shalako** [comment]
I believe this is a documentation error and does not belong in the api spec.

**Comment by bentarnoff** [comment]
Thanks, @shalako. We'll remove it.

**Comment by pspinrad** [comment]
Removed - will publish soon.
