### ISSUE TITLE
Lost TOC on API page

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-services#154]
On http://docs.cloudfoundry.org/services/api.html it seems the latest docs refactoring omitted the convenient table of content that allowed easy discovery of the anchors permalinks 

Would it be easy to restore ?

Thanks in advance,

Guillaume.

**Comment by ljarzynski** [comment]
Thanks @gberche-orange, we should have a change soon that restores the table. I'll keep this issue open until that happens. cc @abbyachau

**Comment by gberche-orange** [comment]
thanks @ljarzynski

**Comment by abbyachau** [comment]
@ljarzynski, think we can close this issue now. The new TOC seems to work.

**Comment by ljarzynski** [comment]
Awesome! Thanks @abbyachau !
