### ISSUE TITLE
Table of Contents links on /services/api.html do not work

### ISSUE THREAD

**Issue by dotchev** [cloudfoundry/docs-services#155]
Go to https://docs.cloudfoundry.org/services/api.html
The links under Table of Contents do not work, which makes it inconvenient to navigate to a particular section.
I use Google Chrome Version 57.0.2987.133 (64-bit) on Mac OSX 10.12.4.

**Comment by animatedmax** [comment]
We build the api.html page from a source repository controlled by the opensservicebrokerapi GitHub organization, and the html page was removed by them per their request of the openservicebrokerapi team: https://github.com/openservicebrokerapi/servicebroker/pull/157. 

The removal of the html from the source files introduced an issue where the links at the top of the page no longer do anything. 

The openservicebrokerapi team is building a tool which may or may not resolve this issue in an optimal way. In the meantime, the links at the top of the api.html page will not work.

**Comment by animatedmax** [comment]
The links in the Table of Contents now work. Thank you for raising this issue, dotchev!
