### ISSUE TITLE
How to encrypt vcap services (CUPS)  environment variables?

### ISSUE THREAD

**Issue by zjesse713** [cloudfoundry/docs-services#156]
Your example shows

VCAP_SERVICES=
{
  cleardb: [
    {
      name: "cleardb-1",
      label: "cleardb",
      plan: "spark",
      credentials: {
        name: "ad_c6f4446532610ab",
        hostname: "us-cdbr-east-03.cleardb.com",
        port: "3306",
        username: "b5d435f40dd2b2",
        password: "ebfc00ac",
        uri: "mysql://b5d435f40dd2b2:ebfc00ac@us-cdbr-east-03.cleardb.com:3306/ad_c6f4446532610ab",
        jdbcUrl: "jdbc:mysql://b5d435f40dd2b2:ebfc00ac@us-cdbr-east-03.cleardb.com:3306/ad_c6f4446532610ab"
      }
    }
  ]

How can I encrypt user name and password do that data values will not be exposed?

**Comment by harishkadamudi** [comment]
Any updates on this request?

**Comment by cf-pub-tools** [comment]
Hi NAME,

This documentation repository is maintained by technical writers, not developers or support engineering. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.

For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io

Thank you.

**Comment by rajendragosavi** [comment]
Any updates on this request ?

**Comment by jncd** [comment]
Hi @rajendragosavi 
No, no updates on this request. It was closed over two years ago. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.
