### ISSUE TITLE
Compatibility of service with new bosh 

### ISSUE THREAD

**Issue by rahul221192** [cloudfoundry/docs-services#161]
Hi 

I am using cassandra Service [Cassandra bosh Service ](https://github.com/emc-cloudfoundry/cassandra-cf-service-boshrelease)  which is not managed now anymore.
i am getting  issue with new bosh version 

**I am using bosh version: '261.4' and cf version: '267'**

i am getting error

_Deploying
---------

Director task 11384
Deprecation: Ignoring cloud config. Manifest contains 'networks' section.

  Started preparing deployment > Preparing deployment

Deprecation: Please use 'templates' when specifying multiple templates for a job. 'template' for multiple templates will soon be unsupported.

. Done (00:00:00)

Error 100: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'cassandra_broker_server'. Errors are:
    - Unable to render templates for job 'cassandra_server'. Errors are:
      - Error filling in template 'cassandra.yaml.erb' (line 10: undefined method `cluster_name' for nil:NilClass)
      - Error filling in template 'cassandra-env.sh.erb' (line 132: undefined method `max_heap_size' for nil:NilClass)
      - Error filling in template 'cassandra-topology.properties.erb' (line 18: Can't find property '["cassandra_server.topology"]')
      - Error filling in template 'log4j-server.properties.erb' (line 35: undefined method `persistent_directory' for nil:NilClass)
    - Unable to render templates for job 'cassandra_broker'. Errors are:
      - Error filling in template 'cassandra-broker-config.properties.erb' (line 3: undefined method `seeds' for nil:NilClass)

Task 11384 error

For a more detailed error report, run: bosh task 11384 --debug
command 'bosh -n --color -t https://xyz:2324 -d /tmp/bosh_manifest20170720-7-19irvv4 deploy' failed!_**

here is my sample manifest file 
[cassandra manifest file.txt](https://github.com/cloudfoundry/docs-services/files/1182332/cassandra.manifest.file.txt)

Its not managed now but if someone can help me out .

Thanks in advance

**Comment by mjgutermuth** [comment]
Hi @rahul221192! Unfortunately, because this BOSH release is no longer maintained, we are unable to provide support for this issue. This BOSH release uses an older manifest format, and deploying it with current versions of BOSH and CF may be causing some of these errors. You can try reaching out to the #bosh channel in [Cloud Foundry Slack](https://slack.cloudfoundry.org/) for help updating your manifest, or use a different Cassandra service broker BOSH release that is still being maintained.
