### ISSUE TITLE
Difficult to read the service broker diagram

### ISSUE THREAD

**Issue by tuzz** [cloudfoundry/docs-services#162]
Hello, it's a bit difficult to read this diagram:
https://github.com/cloudfoundry/docs-services/blob/master/images/managed-services.png

It appears on this page:
https://docs.cloudfoundry.org/services/overview.html

Would it be possible to upload a high resolution version?

Thanks

**Comment by animatedmax** [comment]
Hi @tuzz We've updated the diagram and added a link to a larger version. Thanks!
