### ISSUE TITLE
The purge service guide was too old.

### ISSUE THREAD

**Issue by mma-pivotal** [cloudfoundry/docs-services#172]
According to the following purge-service guide, if I want to remove a service broker without first deleting the service instances binded to it, I should use the `-p` option.

https://docs.pivotal.io/pivotalcf/2-3/services/managing-service-brokers.html#purge-service

However in PCF if I try to remove the service broker with `-p` I got an warning message like below.

```
cf purge-service-offering my-service -p my-service

FAILED
Option '-p' only works up to CF API version 2.46.0. Your target is 2.94.0.
```

Instead if I just ignore the `-p` option it would work.

```
cf purge-service-offering my-service
WARNING: This operation assumes that the service broker responsible for this service offering is no longer available, and all service instances have been deleted, leaving orphan records in Cloud Foundry's database. All knowledge of the service will be removed from Cloud Foundry, including service instances and service bindings. No attempt will be made to contact the service broker; running this command without destroying the service broker will cause orphan service instances. After running this command you may want to run either delete-service-auth-token or delete-service-broker to complete the cleanup.

Really purge service offering aws-rds-aurora from Cloud Foundry?> n
```

Please update the doc (and other PAS that is using CAPI 2.46.0+) with correct information.

**Comment by pspinrad** [comment]
Thanks @mma-pivotal -- do you know if the service is from a v1 broker?  Maybe the docs just aren't clear enough that you usually don't need `-p PROVIDER` unless it's an old service broker? @zrob

**Comment by zrob** [comment]
We can probably remove or make the notes about v1 brokers much less prominent.  v1 brokers have been gone for years

**Comment by mma-pivotal** [comment]
@pspinrad no I am using a v2 broker.

**Comment by pspinrad** [comment]
Thanks @zrob @mma-pivotal -- yeah, the command example shown is for v1 and the point about v1 needing `-p PROVIDER` is buried -- will fix...
