### ISSUE TITLE
Azure LB and AWS LB are not working properly with route service

### ISSUE THREAD

**Issue by pivotal-yuliya-verbishchuk** [cloudfoundry/docs-services#180]
Hello team, 

can you please specify in the docs that Azure and AWS LB are causing 502s when using the route service, the reason is because the gorouter is initiating the route service callout and is the source IP of the route service TCP connection which can’t happen if it’s load balancing back to itself.

So the LB will cause 502 timeout and will never be forwarded to the app. 
Thank you.

**Comment by mlimonczenko** [comment]
Hello @pivotal-yuliya-verbishchuk,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
