### ISSUE TITLE
syslog_drain_url description confusing

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/docs-services#37]
It says here http://docs.cloudfoundry.org/services/api.html#binding "A URL to which Cloud Foundry should drain logs to for the bound application." Aside from the superfluous (second) "to" this is really not enough information to know what it's for. Does Cloud Foundry pipe the application logs (stdout etc.) from any app that is bound to this service to the indicated URL? Or is it a URL that I can use to download the logs from the application? What happens if more than one service is bound? Do you get more than one URL? How does that make sense (seems like it's related to the app not the service from the description above)? Or is it a URL I can get the stdout from the service instance itself (e.g. assuming it is a process that emits logs)?

**Comment by animatedmax** [comment]
24 November 2014 - Documentation updated - 
https://www.pivotaltracker.com/story/show/81577356
