### ISSUE TITLE
"cf add-service-broker" should be "cf create-service-broker"

### ISSUE THREAD

**Issue by mmc2004jp** [cloudfoundry/docs-services#49]
In this image (http://docs.cloudfoundry.org/services/images/v2services-new.png), I guess "cf add-service-broker" should be "cf create-service-broker" now.

**Comment by shalako** [comment]
Hello, you are correct. We'll get that image updated asap.
Thank you

**Comment by shalako** [comment]
Fixed. Thank you!

http://docs.cloudfoundry.org/services/api.html#api-overview
