### ISSUE TITLE
Change location of sample Java service brokers

### ISSUE THREAD

**Issue by scottfrederick** [cloudfoundry/docs-services#98]
The project formerly known as `Spring Boot CF Service Broker` has been re-branded and moved. It is now `Spring Cloud - Cloud Foundry Service Broker` and lives at https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker. 

The sample app for this project is in the process of being moved from https://github.com/spgreenberg/spring-boot-cf-service-broker-mongo to https://github.com/spring-cloud-samples/cloudfoundry-mongodb-service-broker. 

The links here should be changed to reflect these changes: https://github.com/cloudfoundry/docs-services/blob/master/examples.html.md.erb#L16

**Comment by bentarnoff** [comment]
Thanks, @scottfrederick! We have renamed the project in our "Example Service Brokers," which you can see here: http://docs.cloudfoundry.org/services/examples.html
